import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";  

import Logo from "../assets/logo.png";
import Logo2 from "../assets/logo2.png";

import {
  FaChartLine,
  FaGlobe,
  FaRobot,
  FaUser,
  FaPhone,
  FaInstagram,
  FaXTwitter,
  FaLinkedin,
  FaFax
} from "react-icons/fa6";

import "../styles/HomePage.css";

export default function HomePage() {
  const navigate = useNavigate();
  const [showMenu, setShowMenu] = useState(false);

  const { logout } = useAuth();

  useEffect(() => {
    const sections = document.querySelectorAll(".reveal");

    const revealOnScroll = () => {
      sections.forEach(section => {
        const top = section.getBoundingClientRect().top;
        if (top < window.innerHeight - 100) {
          section.classList.add("active");
        }
      });
    };

    window.addEventListener("scroll", revealOnScroll);
    revealOnScroll();
    return () => window.removeEventListener("scroll", revealOnScroll);
  }, []);

  return (
    <div className="home-root">

      <header className="navbar">
        <img src={Logo2} className="nav-logo" alt="navbar logo" />

        <nav className="nav-links">
          <button className="nav-btn" onClick={() => window.location.href="#about"}>About</button>
          <button className="nav-btn" onClick={() => window.location.href="#services"}>Services</button>
          <button className="nav-btn" onClick={() => window.location.href="#contact"}>Contact</button>
        </nav>

        <div className="profile-wrapper">
          <FaUser
            className="profile-icon"
            onClick={() => setShowMenu(!showMenu)}
          />

          {showMenu && (
            <div className="dropdown-menu">
              <p onClick={() => navigate("/profile")}>My Profile</p>
              <p onClick={() => navigate("/projects")}>My Projects</p>

           
              <p
                onClick={async () => {
                  await logout();     
                  navigate("/");     
                }}
              >
                Logout
              </p>
            </div>
          )}
        </div>
      </header>

      <section className="hero reveal">
        <div className="hero-left">
          <h1 className="hero-title">Smart AI Tools for Smarter Business Decisions.</h1>
          <p className="hero-desc">Moqaddim gives you fast, clear insights instantly.</p>
        </div>

        <div className="hero-right">
          <img src={Logo} className="hero-logo-img float-soft" alt="hero-logo" />
        </div>
      </section>

      <section id="about" className="about reveal">
        <h2 className="section-title">About Moqaddim</h2>
        <p className="about-text">
          Moqaddim is an AI-powered platform developed in 2025 by IT students as a senior graduation project.
          It helps entrepreneurs transform ideas into structured and data-driven opportunities using
          modern and intelligent digital tools. Since launch, the platform has been recognized for clarity,
          reliability, and practical market value.
        </p>
      </section>

      <section id="services" className="services reveal">
        <h2 className="section-title">Our Services</h2>

        <div className="service-grid">

          <div className="service-card clickable" onClick={() => navigate("/new-study")}>
            <FaRobot className="service-icon" />
            <h3>AI Feasibility Reports</h3>
            <p>Instant feasibility studies generated by Moqaddim's internal AI engine.</p>
          </div>

          <div className="service-card" onClick={() => navigate("/tools")}>
            <FaGlobe className="service-icon" />
            <h3>Currency Converter</h3>
            <p>Accurate financial conversions for entrepreneurs.</p>
          </div>

          <div className="service-card coming-soon">
            <FaChartLine className="service-icon" />
            <h3>Market Analysis</h3>
            <p>Advanced market insights and competitor analysis coming soon.</p>
          </div>

        </div>
      </section>

      <section id="contact" className="contact-section reveal">
        <h2 className="contact-title">Contact Us</h2>

        <div className="contact-grid">

          <div className="contact-item">
            <FaPhone className="contact-icon" />
            <div>
              <h4>Phone</h4>
              <p>+966 555 000 111</p>
            </div>
          </div>

          <div className="contact-item">
            <FaXTwitter className="contact-icon" />
            <div>
              <h4>X (Twitter)</h4>
              <p>@moqaddim_ai</p>
            </div>
          </div>

          <div className="contact-item">
            <FaInstagram className="contact-icon" />
            <div>
              <h4>Instagram</h4>
              <p>@moqaddim.app</p>
            </div>
          </div>

          <div className="contact-item">
            <FaLinkedin className="contact-icon" />
            <div>
              <h4>LinkedIn</h4>
              <p>linkedin.com/company/moqaddim</p>
            </div>
          </div>

          <div className="contact-item">
            <FaFax className="contact-icon" />
            <div>
              <h4>Fax</h4>
              <p>+966 12 123 4567</p>
            </div>
          </div>

          <div className="contact-item">
            <FaGlobe className="contact-icon" />
            <div>
              <h4>Location</h4>
              <p>Jeddah, Saudi Arabia</p>
            </div>
          </div>

        </div>
      </section>

      <footer className="footer reveal">
        © 2025 Moqaddim — All Rights Reserved
      </footer>

    </div>
  );
}
